### PR TITLE
Add UTF-8 Support

### PR DESCRIPTION
**Pull request by iamaldi**
Hey there!

It has occurred recently that AuthMatrix could not save the results to a file due to non-ascii data being present in the HTTP request(s)/response(s). Specifically, the issue lies in the fact that when Base64 encoding, AuthMatrix does not account for non-ascii  characters. For example, the following HTTP request containing Greek characters cannot be saved by AuthMatrix.

```http
POST / HTTP/1.1
Host: 127.0.0.1
Cache-Control: max-age=0
Upgrade-Insecure-Requests: 1
Content-Type: application/json; charset=utf-8;
User-Agent: Mozilla/5.0 [...]
Accept: text/html[...]
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.9
Connection: close
Content-Length: 31

{"username":"Γεια σου κόσμε!"}
```

With that being said, encoding the string resources to UTF-8 prior to Base64 encoding mitigates the issue.
At the moment, this issue is resolved by adding the UTF-8 encoding on lines 1830-1831.
https://github.com/SecurityInnovation/AuthMatrix/blob/3736d7a6cc5ef5f4dd4359537e1279aa5fa29ac7/AuthMatrix.py#L1830-L1831

However, I also implemented the same changes on every ```base64.b64encode()``` instance to prevent similar occurrences (although might not be neccessary - e.g. cookies).

Looking forward to your comments.

Cheers,
Aldi

### CODE REVIEW

**Comment by iamaldi** [comment]
@benstew Is there an ETA on this?

**Comment by kairis** [comment]
Thanks, this fixed the issue for me.
Without this, I was getting `UnicodeEncodeError: 'ascii' codec can't encode characters in position 1072-1075: ordinal not in range(128)` in the Extender error tab.

**Review by benstew — APPROVED** [review]
@iamaldi - Thanks for this addition! Very well written PR and straight forward code change. LGTM!

**Comment by iamaldi** [comment]
@benstew
Thank you for accepting this contribution. Is it possible to also update the remote repository of the extension at https://github.com/portswigger/auth-matrix so users can update to the latest version via Burp Extender?

**Pull request merged**
